# This file is auto-generated by the code_generator (one-time action)
#
# Cookbook Name:: librenms
# Spec:: default
#
# Copyright:: 2017, The Authors, All Rights Reserved.

require 'spec_helper'

describe 'librenms::default' do
end
