# This file is auto-generated by the code_generator (one-time action)
#
# Cookbook Name:: chef-librenms
# Spec:: default
#
# Copyright:: 2017, The Authors, All Rights Reserved.

require 'spec_helper'

describe 'chef-librenms::default' do
end
